export const MISSION_TYPES = {
  flyby: {
    id: 'flyby',
    label: 'Flyby Survey',
    duration: 15,
    priority: 1,
    description: 'Quick orbital survey of the planet',
    stageRequirement: 1,
  },
  collect_samples: {
    id: 'collect_samples',
    label: 'Collect Samples',
    duration: 45,
    priority: 3,
    description: 'Gather geological samples',
    stageRequirement: 1,
  },
  deploy_equipment: {
    id: 'deploy_equipment',
    label: 'Deploy Equipment',
    duration: 60,
    priority: 4,
    description: 'Set up scientific instruments',
    stageRequirement: 2,
  },
  build_base: {
    id: 'build_base',
    label: 'Build Base',
    duration: 120,
    priority: 5,
    description: 'Establish a permanent outpost',
    stageRequirement: 2,
  },
  explore_surface: {
    id: 'explore_surface',
    label: 'Explore Surface',
    duration: 90,
    priority: 3,
    description: 'Extended surface exploration',
    stageRequirement: 3,
  },
  establish_colony: {
    id: 'establish_colony',
    label: 'Establish Colony',
    duration: 240,
    priority: 5,
    description: 'Full colonization mission',
    stageRequirement: 4,
  },
};
